"""Signals: the out-of-sample predictions on the chart, bar by bar.

This is where a study stops being a table of ratios and becomes something you
can argue with — every position the model took, on the price it took it at, in
the regime it was taken in.
"""

from __future__ import annotations

import streamlit as st
import theme


def render(selection: dict, config) -> None:
    from qmr.experiments.store import list_experiments, load_experiment

    st.markdown(
        theme.lede(
            "Out-of-sample predictions plotted on the price that produced them. "
            "Every marker below was generated by a model that had never seen the "
            "bar it is trading — and every one was executed at the <i>next</i> "
            "bar's open, never the close it was computed from."
        ),
        unsafe_allow_html=True,
    )

    records = list_experiments()
    if not records:
        st.info(
            "No studies stored yet. Run one on the **Run a study** tab first.",
        )
        return

    options = [record.run_id for record in records]
    labels = {r.run_id: f"{r.summary.get('label', r.run_id)}  ·  {r.created_at[:16].replace('T', ' ')}" for r in records}
    default = st.session_state.get("last_run_id")
    index = options.index(default) if default in options else 0

    run_id = st.selectbox("Study", options, index=index, format_func=lambda k: labels[k], key="sig_run")

    try:
        record = load_experiment(run_id)
    except Exception as exc:
        st.error(f"Could not load {run_id}: {exc}")
        return

    predictions = record.get("predictions")
    price = record.get("price")
    equity = record.get("equity")
    summary = record["summary"]

    if predictions is None or predictions.empty or price is None:
        st.warning("This study has no stored predictions.")
        return

    # -- the latest call ---------------------------------------------------
    latest = predictions.iloc[-1]
    direction = {1: "LONG", -1: "SHORT", 0: "FLAT"}[int(latest["prediction"])]
    confidence = float(max(latest["p_long"], latest["p_short"], latest["p_flat"]))

    st.markdown(
        theme.stat_tiles(
            [
                ("Most recent call", direction, f"as of {predictions.index[-1]:%Y-%m-%d %H:%M}"),
                ("Confidence", f"{confidence * 100:.1f}%", "winning class probability"),
                ("P(long)", f"{latest['p_long'] * 100:.1f}%", "model probability"),
                ("P(short)", f"{latest['p_short'] * 100:.1f}%", "model probability"),
                (
                    "Positions taken",
                    f"{int((predictions['prediction'] != 0).sum()):,}",
                    f"of {len(predictions):,} bars scored",
                ),
            ]
        ),
        unsafe_allow_html=True,
    )

    st.markdown(
        theme.note(
            "This is the model's reading of the last bar in the study window, not "
            "trading advice and not a live signal — the study window ends where "
            "the stored history ends. Refresh the history with "
            "<code>qmr export-mt5</code> and rerun the study to move it forward."
        ),
        unsafe_allow_html=True,
    )

    # -- chart -------------------------------------------------------------
    st.divider()
    controls = st.columns([1, 1, 2])
    with controls[0]:
        window = st.select_slider(
            "Bars shown", options=[250, 500, 1000, 2500, 5000], value=1000, key="sig_window"
        )
    with controls[1]:
        show_regimes = st.checkbox("Shade regimes", value=True, key="sig_regimes")

    view_predictions = predictions.iloc[-window:]
    view_price = price.reindex(view_predictions.index)

    regime_names: dict[int, str] = {}
    regime_table = record.get("regime_performance")
    if regime_table is not None and not regime_table.empty:
        # Recover the readable names by matching the stored ordering.
        for state in sorted(view_predictions["regime"].unique()):
            regime_names[int(state)] = f"Regime {int(state)}"
    transitions = record.get("regime_transitions")
    if transitions is not None and not transitions.empty:
        stored_names = transitions.iloc[:, 0].tolist()
        for state, name in enumerate(stored_names):
            regime_names[state] = str(name)

    st.plotly_chart(
        theme.price_chart(
            view_price,
            regimes=view_predictions["regime"] if show_regimes else None,
            regime_names=regime_names,
            signals=view_predictions["prediction"],
            title=f"{summary.get('symbol')} {summary.get('timeframe')} — out-of-sample positions",
            height=480,
        ),
        use_container_width=True,
    )

    # -- probability stream -------------------------------------------------
    st.markdown("#### Model conviction over time")
    st.markdown(
        theme.lede(
            "The probability the model assigns to each direction. Long stretches "
            "hugging the middle are the model telling you it does not know — which "
            "is more useful information than a forced call."
        ),
        unsafe_allow_html=True,
    )

    st.plotly_chart(
        theme.line_chart(
            {
                "P(long)": view_predictions["p_long"] * 100,
                "P(short)": view_predictions["p_short"] * 100,
                "P(flat)": view_predictions["p_flat"] * 100,
            },
            title="Class probabilities",
            axis_title="Probability (%)",
            value_format=".1f",
            height=300,
        ),
        use_container_width=True,
    )

    threshold = float(summary.get("decision_threshold", 0.5))
    st.caption(
        f"A position is taken only when the winning class clears {threshold:.0%}. "
        "All three series are probabilities, so they share one axis."
    )

    # -- position record ----------------------------------------------------
    st.divider()
    left, right = st.columns([1.2, 1], gap="large")

    with left:
        st.markdown("#### Where the money was made and lost")
        if equity is not None and not equity.empty:
            view_equity = equity.reindex(view_predictions.index)
            st.plotly_chart(
                theme.equity_chart(
                    view_equity["equity"].dropna(),
                    view_equity["benchmark_equity"].dropna(),
                    title="Equity over the window shown above",
                    height=320,
                ),
                use_container_width=True,
            )

    with right:
        st.markdown("#### Position mix")
        mix = view_predictions["prediction"].value_counts(normalize=True)
        st.plotly_chart(
            theme.bar_chart(
                ["Long", "Flat", "Short"],
                [float(mix.get(k, 0.0) * 100) for k in (1, 0, -1)],
                title="Share of bars, window shown",
                axis_title="Share (%)",
                value_format=".1f",
                height=320,
            ),
            use_container_width=True,
        )

    # -- trades and export --------------------------------------------------
    trades = record.get("trades")
    if trades is not None and not trades.empty:
        with st.expander("Round trips in this study", expanded=False):
            recent = trades.tail(60).copy()
            st.dataframe(recent.round(6), use_container_width=True, hide_index=True)

    export = view_predictions.copy()
    export.index.name = "timestamp"
    st.download_button(
        "Download the out-of-sample signal series",
        export.to_csv().encode("utf-8"),
        file_name=f"{run_id}_signals.csv",
        mime="text/csv",
    )
